/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import pkgCalc.ControllerCalc;
import pkgCalc.ModelCalc;
import pkgCalc.ViewCalc;

/**
 *
 * @author schueler
 */
public class CalcApp extends javax.swing.JFrame {

    private ViewCalc view;
    private ModelCalc model;
    private ControllerCalc controller;

    /**
     * Creates new form CalcApp
     */
    public CalcApp() {
        initComponents();
        initMVCComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container_controller = new javax.swing.JPanel();
        container_view = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container_controller.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout container_controllerLayout = new javax.swing.GroupLayout(container_controller);
        container_controller.setLayout(container_controllerLayout);
        container_controllerLayout.setHorizontalGroup(
            container_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        container_controllerLayout.setVerticalGroup(
            container_controllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        container_view.setBackground(new java.awt.Color(247, 167, 87));

        javax.swing.GroupLayout container_viewLayout = new javax.swing.GroupLayout(container_view);
        container_view.setLayout(container_viewLayout);
        container_viewLayout.setHorizontalGroup(
            container_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        container_viewLayout.setVerticalGroup(
            container_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container_controller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container_controller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(container_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container_controller;
    private javax.swing.JPanel container_view;
    // End of variables declaration//GEN-END:variables

    private void initMVCComponents() {
        view = new ViewCalc();
        model = new ModelCalc();
        controller = new ControllerCalc(view,model);
        model.addObserver(view);
        model.addObserver(controller);
        
        this.container_view.add(view);
        this.container_controller.add(controller);
        
    }
}
