/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingcar;

/**
 *
 * @author schueler
 */
public class GUI_Car extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Car
     */
    public GUI_Car() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setText("car-id");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtName.setText("carname");
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        lblMessage.setBackground(new java.awt.Color(238, 141, 45));
        lblMessage.setText("message");
        lblMessage.setOpaque(true);
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, -1));

        btnGo.setText("go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelected(evt);
            }
        });
        getContentPane().add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelected
        lblMessage.setText("button pressed");
    }//GEN-LAST:event_buttonSelected



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
