/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgGUI;

import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import pkgDATA.Database;
import pkgDATA.EventCellException;
import pkgDATA.EventDriverChanged;
import pkgDATA.EventLogBookChanged;
import pkgDATA.Journey;
import pkgDATA.JourneyTableModle;

/**
 *
 * @author schueler
 */
public class journeyGUI extends javax.swing.JFrame implements JourneyTableModle.OnEventCellExceptionListener, Observer{

    /**
     * Creates new form journeyGUI
     */
    public journeyGUI(Database newdb) {
        this.db = newdb;
        jtm = new JourneyTableModle(db);
        db.addObserver(jtm);
        initComponents();
        jtm.addOnEventCellExceptionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSelected = new javax.swing.JPanel();
        lblSelected = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuJourney = new javax.swing.JMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSelected.setBackground(java.awt.SystemColor.info);

        lblSelected.setText("...");

        javax.swing.GroupLayout jPanelSelectedLayout = new javax.swing.GroupLayout(jPanelSelected);
        jPanelSelected.setLayout(jPanelSelectedLayout);
        jPanelSelectedLayout.setHorizontalGroup(
            jPanelSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanelSelectedLayout.setVerticalGroup(
            jPanelSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSelectedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelected, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(jtm);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(java.awt.SystemColor.info);

        lblMessage.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMessage)
                .addGap(27, 27, 27))
        );

        jMenuJourney.setText("Journey");

        jMenuItemAdd.setText("Add");
        jMenuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jMenuJourney.add(jMenuItemAdd);

        jMenuItemDelete.setText("delete");
        jMenuJourney.add(jMenuItemDelete);

        jMenuBar1.add(jMenuJourney);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPerformed
        // TODO add your handling code here:
        try {
            if(evt.getSource() == this.jMenuItemAdd){
                this.addJourney();
            }
        } catch (Exception ex) {
            this.lblMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_ActionPerformed

    /**
     * @param args the command line arguments
     */
    private Database db;
    private JourneyTableModle jtm;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenu jMenuJourney;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSelected;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSelected;
    // End of variables declaration//GEN-END:variables

    private void addJourney() throws Exception {
        db.getSelectedLogbook().addJourney(new Journey());
        this.jtm.fireTableDataChanged();
        this.lblMessage.setText("Journey is added.");
    }

    @Override
    public void handleEventCellException(EventCellException ex) {
        this.lblMessage.setText(ex.getMessage());
    }

    @Override
    public void update(Observable o, Object arg) {
        if(db.getSelectedLogbook() != null){
            this.lblSelected.setText("driver " + db.getSelectedDriver() + " logbook " + db.getSelectedLogbook());
        }else
            this.lblSelected.setText("...");
    }
}
